### ISSUE TITLE
verify_tables_structure terminate with exception

### ISSUE THREAD

**Issue by s-medvedev** [GolosChain/cyberway#240]
**Symptom:**
add_abi terminate with exception

**STR:**
1. Start testnet
2. Load contract with abi
3. Change abi

**Actual result:**
SIgnal `setabi` failed with error. Nodeos logs contains:
```
warn  2019-01-24T15:56:41.132 thread-0  controller.cpp:286            emit                 ] signal handler threw exception
```

**Expected result:**
Change abi execute successfully

**Additional info:**
GDB at throw exception:
```
Thread 1 "nodeos" hit Catchpoint 4 (exception thrown), 0x00007ffff5e9a8bd in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#0  0x00007ffff5e9a8bd in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000001ef9d62 in bsoncxx::v_noabi::document::element::get_bool() const ()
#2  0x0000000000e8032c in cyberway::chaindb::mongodb_driver::mongodb_impl_::get_db_indexes (this=<optimized out>, db_table=...)
    at /mnt/working/eos-debug.git/libraries/chain/chaindb/mongo_driver.cpp:543
#3  0x0000000000e7fc05 in cyberway::chaindb::mongodb_driver::mongodb_impl_::db_tables(eosio::chain::name const&) const::{lambda()#1}::operator()() const (this=<optimized out>)
    at /mnt/working/eos-debug.git/libraries/chain/chaindb/mongo_driver.cpp:581
#4  0x0000000000e7c31d in cyberway::chaindb::(anonymous namespace)::_detail::auto_reconnect<cyberway::chaindb::mongodb_driver::mongodb_impl_::db_tables(eosio::chain::name const&) const::{lambda()#1}>(cyberway::chaindb::mongodb_driver::mongodb_impl_::db_tables(eosio::chain::name const&) const::{lambda()#1}&&) (lambda=<optimized out>)
    at /mnt/working/eos-debug.git/libraries/chain/chaindb/mongo_driver.cpp:151
#5  cyberway::chaindb::mongodb_driver::mongodb_impl_::db_tables (this=<optimized out>, code=...) at /mnt/working/eos-debug.git/libraries/chain/chaindb/mongo_driver.cpp:565
#6  0x0000000000e7b02d in cyberway::chaindb::mongodb_driver::db_tables (this=<optimized out>, code=...) at /mnt/working/eos-debug.git/libraries/chain/chaindb/mongo_driver.cpp:887
#7  0x0000000000e6d9ab in cyberway::chaindb::abi_info::verify_tables_structure (this=0x7fffffff9ad0, driver=...) at /mnt/working/eos-debug.git/libraries/chain/chaindb/abi_info.cpp:228
#8  0x0000000000e39edd in cyberway::chaindb::chaindb_controller::controller_impl_::set_abi (this=0x2f528d0, code=..., info=...)
    at /mnt/working/eos-debug.git/libraries/chain/chaindb/controller.cpp:506
#9  0x0000000000e380c2 in cyberway::chaindb::chaindb_controller::controller_impl_::set_abi (this=0x2f528d0, code=..., abi=...)
    at /mnt/working/eos-debug.git/libraries/chain/chaindb/controller.cpp:139
```
MongoDB contains next indexes:
```
> db.convert.getIndexes()
[
	{
		"v" : 2,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "_CYBERWAY_gls-vesting.convert"
	},
	{
		"v" : 2,
		"unique" : true,
		"key" : {
			"sender" : 1,
			"_SERVICE_.scope" : 1
		},
		"name" : "primary",
		"ns" : "_CYBERWAY_gls-vesting.convert"
	},
	{
		"v" : 2,
		"key" : {
			"payout_time" : 1,
			"_SERVICE_.scope" : 1,
			"sender" : 1
		},
		"name" : "payouttime",
		"ns" : "_CYBERWAY_gls-vesting.convert"
	}
]
```
**Note:** index with name `_id_` doesn't contain field `unique`

**Comment by afalaleev** [comment]
#PR 241

**Comment by afalaleev** [comment]
PR #242
